### ISSUE TITLE
target_cache.put で KeyError が発生する

### ISSUE THREAD

**Issue by yuma-m** [yupix/mipac#147]
**Describe the bug**
#144 と同様に、`note.get_reactions` を繰り返し実行した際に、`target_cache.put` で Handle されない `KeyError` が発生する場合がありました。

**Code snippets**

Traceback は以下の通りです。

```
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/utils/cache.py", line 102, in wrapper
    hit_item = target_cache.get(key)
               ~~~~~~~~~~~~~~~~^^^^^
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/utils/cache.py", line 66, in get
    raise KeyError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/xxx.py", line 89, in xxx
    reactions = await self.client.note.action.fetch_reactions(note_id=note_id, limit=100, type=":xxx:")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/actions/note.py", line 284, in fetch_reactions
    return await self._client.note.reaction.action.fetch_reactions(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        note_id=note_id, type=type, limit=limit, since_id=since_id, until_id=until_id
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/utils/cache.py", line 107, in wrapper
    target_cache.put(key, res)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/utils/cache.py", line 85, in put
    self._remove_node(self.head_node.next)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/utils/cache.py", line 48, in _remove_node
    del self.items[node.key]
        ~~~~~~~~~~^^^^^^^^^^
```

**To Reproduce**

以下のようなコードを定期的に繰り返し実行した際に発生します。

```python
reactions = await client.note.action.fetch_reactions(note_id=note_id)
```

**Expected behavior**

https://github.com/yupix/MiPAC/blob/5ecc256969748fff701c28b055900bf3967ebb2b/mipac/utils/cache.py#L105-L108

上記 `except` 内の `target_cache.put(key, res)` で Exception が発生しない。

**Correct behavior**

他の実装を読んでいないので見当外れなことを言っているかもしれませんが、以下が気になった点です。

https://github.com/yupix/MiPAC/blob/5ecc256969748fff701c28b055900bf3967ebb2b/mipac/utils/cache.py#L77-L78

上記の `del self.items[key]` は `self._remove_node(self.items[key])` とすべき？
また、複数のコルーチンから `LRUCache` への操作が発生しても大丈夫でしょうか？

**Screenshots**

N/A

**Environment used:**

* OS: Ubuntu 22.04
* Python: 3.13
* MiPAC: 0.7.1

**Comment by yupix** [comment]
ご報告ありがとうございます。
前回と同様にエラーでご迷惑をおかけして申し訳ないです。

朝は少し作業する時間が取れないので、昼頃か夕方に調査させて頂きます。

> 上記の del self.items[key] は self._remove_node(self.items[key]) とすべき？

その可能性は結構高いので調査の際に確認させて頂きます🙏

> また、複数のコルーチンから LRUCache への操作が発生しても大丈夫でしょうか？

複数のコルーチンからのアクセスは問題ないと考えています

**Comment by yupix** [comment]
LRUCacheを作成した際に `fetch_` 系での動作確認を忘れていたみたいで、全く気づきませんでした。

> 上記の del self.items[key] は self._remove_node(self.items[key]) とすべき？

で解決しそうなので v0.7.2をリリースしますのでそちらで解決するようでしたらIssueをクローズしていただけると助かります。

**Comment by yupix** [comment]
リリースしたのでお手数ですが確認のほどよろしくお願いします。

https://pypi.org/project/mipac/0.7.2/

**Comment by yuma-m** [comment]
@yupix スピーディなご対応、どうもありがとうございます。アップデートの上、しらばく運用して問題なさそうであれば Close するようにいたします。

**Comment by yuma-m** [comment]
@yupix 五月雨式にすみません。0.7.2 に上げたところ以下のようなエラーが発生するので、[5ecc256](https://github.com/yupix/MiPAC/commit/5ecc256969748fff701c28b055900bf3967ebb2b) と対応する下記の行の削除が必要そうです。

https://github.com/yupix/MiPAC/blob/8a2f586379ca2466b85c7e687755a88fda414768/mipac/models/user.py#L47

```
  File "/home/xxx/main.py", line 12, in <module>
    from mipac import Note
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/__init__.py", line 15, in <module>
    from .actions import *
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/actions/__init__.py", line 1, in <module>
    from .admins import *
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/actions/admins/__init__.py", line 1, in <mo>
    from .admin import *
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/actions/admins/admin.py", line 7, in <modul>
    from mipac.models.admin import IndexStat, ModerationLog, ServerInfo, UserIP
  File "/home/xxx/.local/lib/python3.13/site-packages/mipac/models/__init__.py", line 12, in <module>
    from .user import *
AttributeError: module 'mipac.models.user' has no attribute 'UserRole'
```

**Comment by yupix** [comment]
申し訳ないです。
こちらでもそれは出てたのですがコミットするのを忘れてました、今から再度リリースさせて頂きます

**Comment by yupix** [comment]
v0.7.3としてリリースしました

https://pypi.org/project/mipac/0.7.3/

**Comment by yuma-m** [comment]
1点質問です。
`client.note.action.fetch_reactions(note_id="xxx", limit=xxx, type=":xxx:")` が `None` を返す場合があるのですが、想定通りの挙動でしょうか？ Type Hints では戻り値が `list[NoteReaction]` となっているので気になりました。
https://github.com/yupix/MiPAC/blob/a75c05027218609bdc6b6dc0472a9886094bc801/mipac/actions/note.py#L275-L283

以下の `fetch_reaction` 内で、`cache(override=False)` の `get_reactions` を呼び出している部分が気になったのですが、もし私のアプリケーション側での fetch/get メソッドの使い分け等が間違っているようでしたら教えて下さい。自身の過去の発言に対するリアクションを定期的に取得する処理で利用しております。
https://github.com/yupix/MiPAC/blob/a75c05027218609bdc6b6dc0472a9886094bc801/mipac/actions/reaction.py#L92-L104

**Comment by yupix** [comment]
質問の方に関してはこちらの想定としてはNoneは返すつもりがないのでバグです。他の点については現在まだ自宅ではないので帰宅後に確認します。

**Comment by yupix** [comment]
> 以下の fetch_reaction 内で、cache(override=False) の get_reactions を呼び出している部分が気になったのですが、もし私のアプリケーション側での fetch/get メソッドの使い分け等が間違っているようでしたら教えて下さい。自身の過去の発言に対するリアクションを定期的に取得する処理で利用しております。

スマホで軽くコードを見た感じ本来fetchでリクエストをやるはずがほとんどの箇所でgetで行ってしまっているのが原因かもしれません。

**Comment by yupix** [comment]
このissueでやるのは少し範囲外な気がするので新しいissueを作成しました。 #149

**Comment by yupix** [comment]
fetch,getに関係なく今回の不具合は `cache` デコレータにてキーが見つからなかった場合に対応した動作が無かったことのようです、今動作確認をある程度したのでリリースします

**Comment by yupix** [comment]
v0.7.4で上記の問題は修正できたかと思います。
度々申し訳ございませんが、再度更新のほどよろしくお願いします。

https://pypi.org/project/mipac/0.7.4/

**Comment by yuma-m** [comment]
いつも素早いご対応、どうもありがとうございます🙏 
v0.7.4 でしばらく挙動を確認させていただきます。

**Comment by yuma-m** [comment]
4〜5日ほど運用しておりますが、特に問題なさそうですので Close いたします。ご対応どうもありがとうございました！

**Comment by yupix** [comment]
検証ありがとうございます。お手数おかけして申し訳ないです。いつもバグ報告助かってます。また何かありましたらご連絡くだされば幸いです🙏
